config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'images#index'

  # login session routes
  get '/sign_in', to: 'sessions#new', as: :sign_in
  post '/sign_in', to: 'sessions#create', as: :attempt_sign_in
  delete '/sign_out', to: 'sessions#destroy', as: :sign_out

  # image upload & list routes
  resources :images, only: [:index, :new, :create] do
    get :tweet
  end

  # oauth routes for MyTweetApp
  get 'oauth/callback', to: 'oauth_tweet_image#callback'
  get 'oauth/authorize', to: 'oauth_tweet_image#authorize'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :title, presence: true, length: {maximum: 30}
  validate :image_attached?

  # display images of targeted user only
  scope :user_wise, ->(user) { where(user_id: user.id)}

  # get images descending order
  scope :order_updated_at, -> { order(updated_at: :desc)}

  private

  # if image not attached then return required error
  def image_attached?
    errors.add(:image_attached, I18n.t('E0003')) unless photo.attached?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # user_name must be reuqired, length between 10 to 30, must be uniq
  validates :user_name, presence: true,
                        length: {minimum:10, maximum:30},
                        format: {with: /\A[a-zA-Z0-9]+\Z/},
                        uniqueness: true

  has_secure_password
  # password must be reuqired, miminum 8 character
  validates :password, presence: true,
                       length: {minimum:8}

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Authentication
  include SessionHelper
  include OauthTweetImageHelper

end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_user
  end

  # start session of log in user
  def sign_in(user)
    reset_session
    session[:user_name] = user&.user_name
  end

  #end session of log in user
  def sign_out
    session.delete(:user_name)
    session.delete(:token)
    session.delete(:tweet_token)
    @current_user = nil
    reset_session
  end

  # if user not authenticated then did not allow access controller method & actions
  def authenticate_user
    unless is_sign_in?
      redirect_to sign_in_path, error: t('E0001')
    end
  end

end

app/controllers/concerns/form_validate.rb
module FormValidate
  class SignIn
    include ActiveModel::Validations
    attr_accessor :user_name, :password

    validates :user_name, presence: true
    validates :password, presence: true

    def initialize(params = {})
      @user_name = params[:user_name]
      @password = params[:password]
      params.permit(:user_name, :password)
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  # list of images for sign in user
  def index
    @images = Image.user_wise(current_user).order_updated_at
  end

  def new
    @image = Image.new
  end

  #upload image to server
  def create
    @image = current_user.images.build(image_params)
    if @image.save
      redirect_to images_path, notice: I18n.t('I0001')
    else
      render :new
    end
  end

  #image tweet to MyTweetApp
  def tweet
    image = Image.find_by(id: params[:image_id])
    tweet_image = {
      text: image.try(:title),
      url: url_for(image.photo)
    }
    response = TweetApi.post_api(url: "#{Rails.application.secrets.site_path}/api/tweets", body: tweet_image,token: get_auth_token)
    if response.code == "201"
      redirect_to root_url, notice: I18n.t('I0002')
    else
      redirect_to root_url, error: I18n.t('E0004')
    end
  end

  private
  # strong params for image form
  def image_params
    params.require(:image).permit(:title, :photo)
  end

end

app/controllers/oauth_tweet_image_controller.rb
class OauthTweetImageController < ApplicationController

  # get authorization code from MyTweetApp
  def authorize
    redirect_to AuthMyTweetApp.auth_url
  end

  # get callback from MyTweetApp
  def callback
    response = AuthMyTweetApp.get_token(params['code'])
    if response
      # if MyTweetApp reject for authorize to tweet then it will return error
      if response['error_description'].present?
        redirect_to images_path,error: response['error_description']
      # if MyTweetApp reject for authorize to tweet then it will give token
      elsif response['access_token'].present?
        set_auth_token(response['access_token'])
        redirect_images_path
      end
    else
      redirect_images_path
    end
  end

  private
  def redirect_images_path
    redirect_to images_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]

  # if user already login then redirect to dashboard directly
  def new
    redirect_to root_path if is_sign_in?
  end

  # authenticate user information & allow to access image screens
  def create
    user_sign_in_params; return if performed?
    user = User.find_by(user_name: params[:session][:user_name])
    if user&.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to root_path
    else
      flash[:error] = t('E0002')
      render :new
    end
  end

  # destroy session
  def destroy
    sign_out if is_sign_in?
    redirect_to sign_in_path
  end

  private

  # validate data & permit strong parameter
  def user_sign_in_params
    @user = FormValidate::SignIn.new(params[:session])
      render :new unless @user.valid?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # display title of each page
  def page_title(title)
    content_for(:title) { title }
  end

end

app/helpers/oauth_tweet_image_helper.rb
module OauthTweetImageHelper

  # store authorize token
  def set_auth_token(token)
    session[:tweet_token] = token
  end

  # token is present then true otherwise false
  def authorized?
    session[:tweet_token].present?
  end

  # return authentication token if authorized
  def get_auth_token
    session[:tweet_token] if authorized?
  end

end

app/helpers/session_helper.rb
module SessionHelper

  #return current signin user object
  def current_user
    if session[:user_name]
      @current_user ||= User.find_by(user_name: session[:user_name])
    end
  end

  #user already sign in then return true otherwise false
  def is_sign_in?
    current_user.present?
  end

end

app/views/images/_form.html.erb
<%= render partial: 'shared/errors', locals: { object: @image } %>
<div>
  <%= form_for @image do |f| %>
    <div class="field">
      <%= f.label t('image_upload.image_title') %>
      <%= f.text_field :title, value: params[:image].present? ? params[:image][:title] : nil, tabindex: 0 %>
    </div>
    <div class="field">
      <%= f.label t('image_upload.image_file') %>
      <%= f.file_field :photo, tabindex: 1 %>
    </div>
    <div class="field">
      <%= f.submit t('button.upload'), tabindex: 2 %>
      <%= link_to t('button.cancel'), images_path, tabindex: 3 %>
    </div>
  <% end %>
</div>

app/views/images/_image.html.erb
<div class="content-block">
  <div class="block-title">
    <%= image.title %>
  </div>
  <div>
    <%= image_tag(image.photo, class: 'block-image') if image.photo.attached?%>
  </div>
  <div class="block-title">
    <%= link_to t('button.tweet'), image_tweet_path(image) if authorized? %>
  </div>
</div>

app/views/images/_tweet_link.html.erb
<% if authorized? %>
  <h4><%= t('image_upload.tweet_app_approve') %></h4>
<% else %>
  <%= link_to t('image_upload.tweet_app_link'), oauth_authorize_path %>
<% end %>

app/views/images/index.html.erb
<% page_title t('image_list.title') %>
<h1><%= t('image_list.title') %></h1>
<%= render 'tweet_link' %>
<div class="field">
  <%= link_to t('image_upload.title'), new_image_path%>
</div>
<%= render @images %>

app/views/images/new.html.erb
<% page_title t('image_upload.title') %>
<h1><%= t('image_upload.title') %></h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('application_name') %> - <%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/alerts' if flash.present? %>
    <%= render 'shared/sign_out' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<div>
  <ul>
    <% if flash[:error] %>
      <li class='text-red'><%= flash[:error] %></li>
    <% end %>
    <% if flash[:notice] %>
      <li><%= flash[:notice] %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_errors.html.erb
<div>
  <ul>
    <% (object&.errors&.full_messages || []).each do |message| %>
      <li class='text-red'><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_sign_out.html.erb
<%= link_to  t('button.sign_out'), sign_out_path, method: :delete if is_sign_in? %>